[target.'cfg(all(target_arch = "arm", target_os = "none"))']

rustflags = [
  "-C", "link-arg=--nmagic",
  # "-C", "relocation-model=ropi-rwpi",
  # "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Tlink.ld",
  "-C", "codegen-units=1",
  "--emit=obj"
]

[build]
target = "thumbv7em-none-eabi"

[target.thumbv7em-none-eabi]
# runner = "/home/zhouyi/.local/xPacks/@xpack-dev-tools/qemu-arm/7.0.0-1.1/.content/bin/qemu-system-gnuarmeclipse --board STM32F4-Discovery -nographic -semihosting-config enable=on,target=native -kernel"
# Switch to enable GDB
runner = "/home/zhouyi/.local/xPacks/@xpack-dev-tools/qemu-arm/7.0.0-1.1/.content/bin/qemu-system-gnuarmeclipse --board STM32F4-Discovery -nographic -semihosting-config enable=on,target=native -S -gdb tcp::3333 -kernel"
